plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sujayarvind.dax90'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sujayarvind.dax90'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.16.0'
}
